### ISSUE TITLE
Conversation Manager fails on file with no audio

### ISSUE THREAD

**Issue by Jeronymous** [linto-ai/platform-conversation-manager#61]
**Bug description**
On a small audio file of 3 sec with no audio content, the conversation fails with "Erreur : une erreur s'est déclenchée pendant le traitement de l'audio"

**To Reproduce**
1. Go to https://convos.linto.ai
2. Click on "Créer une conversation"
3. Choose a wav file with no audio in it. Like this one [empty.zip](https://github.com/linto-ai/platform-conversation-manager/files/10404010/empty.zip)
4. Do not choose any particular service (no punctuation, no speaker identification)
5. Click on "Créer la conversation"
6. Wait a bit and click on the conversation

**Expected behavior**
It should either appear as an empty conversation (where you can just play the audio file).
Or the failure message should be more explicit.

**Screenshots**
![Screenshot from 2023-01-12 17-57-32](https://user-images.githubusercontent.com/22522728/212131137-198424c1-ad81-4eab-8540-870fde61f7c2.png)

**Comment by Houpert** [comment]
Resolve on new release, version 1.0.3
Now an transcription without audio via the new import api should not crash
